#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# One-click VPS deployment script
# Usage: sudo bash deploy.sh
# ============================================================

echo "========================================="
echo "  Digital Goods Platform - VPS Deploy"
echo "========================================="
echo ""

# ----------------------------------------------------------
# 1. Check root / sudo
# ----------------------------------------------------------
if [ "$EUID" -ne 0 ]; then
  echo "[ERROR] Please run as root: sudo bash deploy.sh"
  exit 1
fi

# ----------------------------------------------------------
# 2. Install Docker if not present
# ----------------------------------------------------------
if ! command -v docker &> /dev/null; then
  echo "[*] Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  echo "[OK] Docker installed."
else
  echo "[OK] Docker already installed."
fi

# ----------------------------------------------------------
# 3. Collect configuration
# ----------------------------------------------------------
echo ""
echo "--- Configuration ---"

# BOT_TOKEN
read -rp "Enter your Telegram BOT_TOKEN: " BOT_TOKEN
if [[ ! "$BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
  echo "[WARNING] BOT_TOKEN format looks invalid. Expected: 123456:ABC-DEF..."
  read -rp "Continue anyway? (y/N): " confirm
  [[ "$confirm" != "y" && "$confirm" != "Y" ]] && exit 1
fi

# TRONGRID_API_KEY (optional)
read -rp "Enter TRONGRID_API_KEY (press Enter to skip): " TRONGRID_API_KEY

# Auto-generate secrets
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
SECRET_KEY=$(openssl rand -base64 48 | tr -d '/+=' | head -c 64)

echo ""
echo "[OK] Configuration collected."

# ----------------------------------------------------------
# 4. Generate .env file
# ----------------------------------------------------------
cat > .env << ENVEOF
# Auto-generated by deploy.sh — $(date -Iseconds)

# App
APP_NAME=Digital Goods Platform
DEBUG=false

# Database (container internal network)
DATABASE_URL=postgresql+asyncpg://postgres:${DB_PASSWORD}@postgres:5432/reflex
DB_PASSWORD=${DB_PASSWORD}

# Redis (container internal network)
REDIS_URL=redis://redis:6379/0

# Runtime backends
EXPORT_TASK_BACKEND=db
PUSH_QUEUE_BACKEND=db

# Telegram Bot
BOT_TOKEN=${BOT_TOKEN}

# USDT Payment
TRONGRID_API_KEY=${TRONGRID_API_KEY}
USDT_CONTRACT_ADDRESS=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

# Security
SECRET_KEY=${SECRET_KEY}
ENVEOF

chmod 600 .env
echo "[OK] .env generated (permissions: 600)."

# ----------------------------------------------------------
# 5. Build and start services
# ----------------------------------------------------------
echo ""
echo "[*] Building Docker images (this may take a few minutes)..."
docker compose build

echo "[*] Starting services..."
docker compose up -d

# ----------------------------------------------------------
# 6. Wait for services to be healthy
# ----------------------------------------------------------
echo "[*] Waiting for services to be ready..."
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U postgres &> /dev/null; then
    break
  fi
  sleep 2
done

# Verify all services are running
echo ""
docker compose ps

# ----------------------------------------------------------
# 7. Output results
# ----------------------------------------------------------
SERVER_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "========================================="
echo "  Deployment Complete!"
echo "========================================="
echo ""
echo "  Web Admin:  http://${SERVER_IP}:3000"
echo "  API:        http://${SERVER_IP}:8000"
echo ""
echo "  Default login:"
echo "    Username: admin"
echo "    Password: admin123"
echo ""
echo "--- Useful Commands ---"
echo "  docker compose logs -f          # View all logs"
echo "  docker compose logs -f web      # View web logs"
echo "  docker compose restart web      # Restart web service"
echo "  docker compose down             # Stop all services"
echo "  docker compose up -d --build    # Rebuild and restart"
echo ""
echo "--- Backup Database ---"
echo "  docker compose exec postgres pg_dump -U postgres reflex > backup.sql"
echo ""
