#!/usr/bin/env bash
set -euo pipefail

echo "========================================="
echo "  Digital Goods Platform - VPS Deploy"
echo "========================================="
echo ""

if [ "$EUID" -ne 0 ]; then
  echo "[ERROR] Please run as root: sudo bash deploy.sh"
  exit 1
fi

is_strong_password() {
  local p="$1"
  [[ ${#p} -ge 12 ]] || return 1
  [[ "$p" =~ [a-z] ]] || return 1
  [[ "$p" =~ [A-Z] ]] || return 1
  [[ "$p" =~ [0-9] ]] || return 1
  [[ "$p" =~ [^A-Za-z0-9] ]] || return 1
}

ensure_openssl() {
  if command -v openssl >/dev/null 2>&1; then
    return 0
  fi
  echo "[*] Installing openssl..."
  apt-get update -qq
  apt-get install -y -qq openssl
}

install_docker_if_missing() {
  if command -v docker >/dev/null 2>&1; then
    echo "[OK] Docker already installed."
    return 0
  fi
  echo "[*] Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list >/dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  echo "[OK] Docker installed."
}

collect_config() {
  echo ""
  echo "--- Configuration ---"

  while true; do
    read -rsp "Enter SUPER_ADMIN_PASSWORD (strong password, >=12 chars): " SUPER_ADMIN_PASSWORD
    echo ""
    if ! is_strong_password "$SUPER_ADMIN_PASSWORD"; then
      echo "[ERROR] Weak password. Require upper/lower/digit/symbol and length >= 12."
      continue
    fi
    read -rsp "Confirm SUPER_ADMIN_PASSWORD: " SUPER_ADMIN_PASSWORD_CONFIRM
    echo ""
    if [ "$SUPER_ADMIN_PASSWORD" != "$SUPER_ADMIN_PASSWORD_CONFIRM" ]; then
      echo "[ERROR] Passwords do not match. Try again."
      continue
    fi
    break
  done

  read -rp "Enter TRONGRID_API_KEY (press Enter to skip): " TRONGRID_API_KEY

  DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  SECRET_KEY=$(openssl rand -base64 48 | tr -d '/+=' | head -c 64)

  echo "[OK] Configuration collected."
}

write_env_file() {
  if [ -f .env ]; then
    cp .env ".env.bak.$(date +%Y%m%d%H%M%S)"
  fi
  cat > .env <<EOF
# Auto-generated by deploy.sh -- $(date -Iseconds)

# App
APP_NAME=Digital Goods Platform
DEBUG=false

# Database (container internal network)
DATABASE_URL=postgresql+asyncpg://postgres:${DB_PASSWORD}@postgres:5432/reflex
DB_PASSWORD=${DB_PASSWORD}

# Redis (container internal network, auth required)
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

# Runtime backends
EXPORT_TASK_BACKEND=db
PUSH_QUEUE_BACKEND=db

# USDT Payment
TRONGRID_API_KEY=${TRONGRID_API_KEY}
USDT_CONTRACT_ADDRESS=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

# Security
SECRET_KEY=${SECRET_KEY}
SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}

# Bootstrap hardening
BOOTSTRAP_DEMO_DATA_ENABLED=0
BOOTSTRAP_PURGE_DEMO_DATA=1
EOF
  chmod 600 .env
  echo "[OK] .env generated (permissions: 600)."
}

wait_for_services() {
  echo "[*] Waiting for services to be ready..."
  for i in $(seq 1 45); do
    if docker compose exec -T postgres pg_isready -U postgres >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done

  for i in $(seq 1 45); do
    if docker compose exec -T redis sh -lc 'redis-cli -a "$REDIS_PASSWORD" ping' >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
}

install_docker_if_missing
ensure_openssl
systemctl enable --now docker >/dev/null 2>&1 || true

collect_config
write_env_file

echo ""
echo "[*] Building Docker images (this may take a few minutes)..."
docker compose build

echo "[*] Starting services..."
docker compose up -d

wait_for_services

echo ""
docker compose ps

SERVER_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "========================================="
echo "  Deployment Complete!"
echo "========================================="
echo ""
echo "  Web Admin:  http://${SERVER_IP}:3000"
echo "  API:        http://${SERVER_IP}:8000"
echo ""
echo "  Super admin username: admin"
echo "  Super admin password: (the value you just entered)"
echo "  Bot tokens are configured in the admin panel (not in deploy.sh)."
echo ""
echo "--- Useful Commands ---"
echo "  docker compose logs -f          # View all logs"
echo "  docker compose logs -f web      # View web logs"
echo "  docker compose restart web      # Restart web service"
echo "  docker compose down             # Stop all services"
echo "  docker compose up -d --build    # Rebuild and restart"
echo ""
echo "--- Backup Database ---"
echo "  docker compose exec -T postgres pg_dump -U postgres reflex > backup.sql"
echo ""
